/**
 * Catálogo de verticales para análisis OpenSpot.
 * IDs estables (API) + etiquetas en español + agrupación UI.
 */
export const BUSINESS_TYPES = [
  "bar",
  "pub",
  "cafe",
  "restaurant",
  "fast_food",
  "bakery",
  "ice_cream",
  "nightclub",
  "gym",
  "yoga_pilates",
  "crossfit_box",
  "retail_fashion",
  "retail_shoes",
  "retail_electronics",
  "supermarket",
  "convenience",
  "pharmacy",
  "optician",
  "perfumery",
  "gift_shop",
  "bookstore",
  "pet_shop",
  "florist",
  "hardware",
  "furniture",
  "jewelry",
  "beauty_salon",
  "barbershop",
  "nail_salon",
  "spa",
  "tattoo",
  "dental_clinic",
  "physiotherapy",
  "veterinary",
  "laundry",
  "coworking",
  "real_estate",
  "travel_agency",
  "academy_sport",
  "driving_school",
  "nursery",
  "tutoring",
  "hotel",
  "hostel",
  "garage",
  "car_wash",
  "gas_station",
  "photography",
  "newsagent",
  "phone_repair",
] as const;

export type BusinessType = (typeof BUSINESS_TYPES)[number];

export const BUSINESS_LABELS: Record<BusinessType, string> = {
  bar: "Bar",
  pub: "Pub / cervecería",
  cafe: "Cafetería",
  restaurant: "Restaurante",
  fast_food: "Comida rápida",
  bakery: "Panadería / pastelería",
  ice_cream: "Heladería",
  nightclub: "Discoteca / club nocturno",
  gym: "Gimnasio / fitness",
  yoga_pilates: "Yoga / pilates",
  crossfit_box: "CrossFit / box",
  retail_fashion: "Moda y textil",
  retail_shoes: "Calzado",
  retail_electronics: "Electrónica / tecnología",
  supermarket: "Supermercado / minimercado",
  convenience: "Ultramarinos / tienda de barrio",
  pharmacy: "Farmacia",
  optician: "Óptica",
  perfumery: "Perfumería / cosmética",
  gift_shop: "Regalos / detalle",
  bookstore: "Librería",
  pet_shop: "Mascotas",
  florist: "Floristería",
  hardware: "Ferretería / bricolaje",
  furniture: "Muebles / decoración",
  jewelry: "Joyería / relojería",
  beauty_salon: "Peluquería / estética",
  barbershop: "Barbería",
  nail_salon: "Manicura / nail art",
  spa: "Spa / bienestar",
  tattoo: "Tatuajes / piercing",
  dental_clinic: "Clínica dental",
  physiotherapy: "Fisioterapia",
  veterinary: "Clínica veterinaria",
  laundry: "Tintorería / lavandería",
  coworking: "Coworking",
  real_estate: "Agencia inmobiliaria",
  travel_agency: "Agencia de viajes",
  academy_sport: "Academia deportiva",
  driving_school: "Autoescuela",
  nursery: "Guardería / educación infantil",
  tutoring: "Academia / refuerzo escolar",
  hotel: "Hotel / hostal",
  hostel: "Hostel / pensión",
  garage: "Taller mecánico",
  car_wash: "Lavadero de coches",
  gas_station: "Estación de servicio",
  photography: "Estudio fotográfico",
  newsagent: "Kiosko / prensa",
  phone_repair: "Reparación móviles",
};

export const BUSINESS_GROUPS: { title: string; items: readonly BusinessType[] }[] =
  [
    {
      title: "Hostelería, cafeterías y ocio",
      items: [
        "bar",
        "pub",
        "cafe",
        "restaurant",
        "fast_food",
        "bakery",
        "ice_cream",
        "nightclub",
      ],
    },
    {
      title: "Deporte y salud activa",
      items: ["gym", "yoga_pilates", "crossfit_box", "academy_sport"],
    },
    {
      title: "Retail y comercio",
      items: [
        "retail_fashion",
        "retail_shoes",
        "retail_electronics",
        "supermarket",
        "convenience",
        "pharmacy",
        "optician",
        "perfumery",
        "gift_shop",
        "bookstore",
        "pet_shop",
        "florist",
        "hardware",
        "furniture",
        "jewelry",
        "newsagent",
        "phone_repair",
      ],
    },
    {
      title: "Belleza, bienestar e imagen",
      items: [
        "beauty_salon",
        "barbershop",
        "nail_salon",
        "spa",
        "tattoo",
        "photography",
      ],
    },
    {
      title: "Salud y clínicas",
      items: ["dental_clinic", "physiotherapy", "veterinary"],
    },
    {
      title: "Servicios, oficina y formación",
      items: [
        "laundry",
        "coworking",
        "real_estate",
        "travel_agency",
        "driving_school",
        "nursery",
        "tutoring",
      ],
    },
    {
      title: "Alojamiento",
      items: ["hotel", "hostel"],
    },
    {
      title: "Motor y estaciones",
      items: ["garage", "car_wash", "gas_station"],
    },
  ];

export function isBusinessType(s: string): s is BusinessType {
  return (BUSINESS_TYPES as readonly string[]).includes(s);
}
